### ISSUE TITLE
Not working after 0.8.5 update 

### ISSUE THREAD

**Issue by Sir-Neo** [apcro/leafpicrevived#25] opened 2020-02-26 12:42 UTC
After 0.8.5 update preview of photos stopped working and only through All Media I was able to view photos. I have tried clearing cache with no lick. Then I tried completely uninstalling and re installing. After that LeafPiccompletely brike down.
I am on Xiaomi Mi9 on stock global MIUI 11.
![Screenshot_2020-02-26-14-40-58-250_com alienpants leafpicrevived](https://user-images.githubusercontent.com/61503505/75345789-15190c80-58a6-11ea-878f-f268a90060ef.jpg)
![Screenshot_2020-02-26-14-40-51-367_com alienpants leafpicrevived](https://user-images.githubusercontent.com/61503505/75345792-164a3980-58a6-11ea-952d-8deb14541ad3.jpg)

**Comment by Sir-Neo** [comment] 2020-02-26 15:34
![Screenshot_2020-02-26-17-34-21-334_com alienpants leafpicrevived](https://user-images.githubusercontent.com/61503505/75360318-4c93b300-58be-11ea-99a2-b1604d6b0b0d.jpg)

**Comment by apcro** [comment] 2020-02-28 20:45
Thanks for the detail and the screenshots. There's now been two issues logged against the Xiaomi MI9 - unfortunately I don't have access to one, so I will see what the differences between 0.8.5 and 0.8.4 are and see if I can determine what the probable cause is.

This does seem to be limited to the Xiaomi MI9 at the moment though.

**Comment by apcro** [comment] 2020-03-20 09:02
An update: This is not specific to the Xiami MI9, it appears to be related to issues with Android 10 and some apparently breaking internal changes. I'm going to close this issue as it will be fixed in the next (0.8.6) release, which will be within the next day or two.

**Closed as completed by apcro** 2020-03-20 09:02 UTC

**Comment by apcro** [comment] 2020-03-22 13:04
Another update: Investigating this it appears to be caused by a change made in the implementation of SQLite query handling in API 29, and 0.8.5 was compiled using `compileSdkVersion 29`

I've changed this to use 28 instead and will be releasing 0.8.6 compiled with this API level. The main gallery page is working again on my Android Q device using this configuration.

The way albums are retrieved will need to be rewritten before API 29 can be used for compilation.
